[package]
name = "bevy_wireframe"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.0"
rand = "0.8.5"
# bitflags = "2.6.0"
# bytemuck = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"